### ISSUE TITLE
make is a dependency

### ISSUE THREAD

**Issue by daurnimator** [ziglang/bootstrap#10]
Not mentioned in the readme.

**Comment by andrewrk** [comment]
cmake depends on make

**Comment by daurnimator** [comment]
> cmake depends on make.

Howso?
```
$ pacman -Qi cmake | grep Dep
Depends On      : curl  libarchive  shared-mime-info  jsoncpp  libjsoncpp.so=21-64  libuv  rhash
Optional Deps   : qt5-base: cmake-gui [installed]
```

> Is it even possible to install cmake without make?

Sure. A practical example might be if you're using e.g. the ninja generator.

**Comment by andrewrk** [comment]
Yeah, ok, makes sense then
